WebApp/Controllers/ParkingLotsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Services.IServices;

namespace WebApp.Controllers
{
    [Authorize]
    public class ParkingLotsController : Controller
    {
        private readonly IParkingLotService _webParkingLotService;

        public ParkingLotsController(IParkingLotService parkingLotService)
        {
            _webParkingLotService = parkingLotService;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {

            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["LocationSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var parkingLots = from p in (await _webParkingLotService.GetAllParkingLots()).Value
                              select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                parkingLots = parkingLots.Where(p => p.name.Contains(char.ToUpper(searchString[0]) + searchString[1..])
                                || p.location.Contains(char.ToUpper(searchString[0]) + searchString[1..]));
            }

            parkingLots = sortOrder switch
            {
                "name_desc" => parkingLots.OrderByDescending(p => p.name),
                _ => parkingLots.OrderBy(p => p.name),
            };
            return View(parkingLots.ToList());
        }



        public async Task<IActionResult> Details(int id)
        {
            try
            {
                return View((await _webParkingLotService.GetParkingLotById(id)).Value);
            }
            catch
            {
                return NotFound();
            }
        }
    }
}

WebApp/Controllers/ParkingSpotsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using WebApp.DTO;
using WebApp.Services.IServices;
using System.Threading.Tasks;
using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Web;
using System.Globalization;
using System.Security.Claims;

namespace WebApp.Controllers
{
    public class ParkingSpotsController : Controller {

        private readonly IParkingSpotService _parkingSpotService;
        private readonly IParkingLotService _parkingLotService;

        public ParkingSpotsController(IParkingSpotService parkingSpotService, IParkingLotService parkingLotService) 
        {
            _parkingSpotService = parkingSpotService;
            _parkingLotService = parkingLotService;
        }

        public async Task<ActionResult<IEnumerable<ParkingSpotDTO>>> Index(int id) {
            try {
                ViewData["parkingLotId"] = id;
                ViewBag.parkLotName = _parkingLotService.GetParkingLotById(id).Result.Value.name;
                return View((await _parkingSpotService.GetAllParkingSpots(id)).Value);
            } catch {
                return NotFound();
            }
        }

        public async Task<ActionResult<IEnumerable<ParkingSpotDTO>>> ManagerSpots() {
            try {
                var managerID = HttpContext.User.FindFirst("sub")?.Value;
                ViewBag.parkLotName = _parkingLotService.GetParkingLotsByManagerId(managerID).Result.Value.name;
                ViewData["parkingLotId"] = _parkingLotService.GetParkingLotsByManagerId(managerID).Result.Value.parkingLotID;
                return View((await _parkingSpotService.GetAllParkingSpotsByManagerID(managerID)).Value);
            } catch {
                return NotFound();
            }
        }
        public async Task<ActionResult<IEnumerable<ParkingSpotDTO>>> Free(int id) {
            try {
                ViewData["parkingLotId"] = id;
                ViewBag.parkLotName = _parkingLotService.GetParkingLotById(id).Result.Value.name;
                return View((await _parkingSpotService.GetAllFreeParkingSpots(id)).Value);
            } catch (Exception) 
            {
                return NotFound();
            }
        }

        //public async Task<ActionResult<IEnumerable<ParkingSpotDTO>>> FreeDate(DateTime startDate, DateTime endDate, int id) {
        //    try {
        //        return await _parkingSpotService.GetFreeParkingSpotsByDate(startDate, endDate, id);
        //    } catch (Exception) 
        //    {
        //        return NotFound();
        //    }
        //}

        public async Task<ActionResult<ParkingSpotDTO>> Details(int id, string pSpotId) {
            try 
            {
                ViewData["parkingSpotId"] = pSpotId;
                ViewBag.parkLotName =(await _parkingLotService.GetParkingLotById(id)).Value.name;
                var parkingSpot =(await _parkingSpotService.GetParkingSpotById(id, pSpotId)).Value;
                parkingSpot.parkingLotID = id;
                return View(parkingSpot);
            } catch {
                return NotFound();
            }
        }

        public async Task<IActionResult> Create() {
            ViewBag.allPlotsNames = (await _parkingLotService.GetAllParkingLots()).Value;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ParkingSpotDTO parkingSpotDTO) {
            try {
                var pLotId = parkingSpotDTO.parkingLotID;
                await _parkingSpotService.CreateParkingSpot(parkingSpotDTO, pLotId);
                var pSpotId = parkingSpotDTO.parkingSpotID;
                var id = pLotId;

                /* Return to ParkingLot Index*/
                return RedirectToAction("ManagerSpots", "ParkingSpots", new { id });

                /* Return to ParkingSpot Details*/
                //return RedirectToAction("Details", "ParkingSpots", new { id, pSpotId } );
            } catch (Exception) {
                return BadRequest();
            }
        }

        public async Task<IActionResult> Edit(int id, string pSpotId) {
            ViewData["parkingLotId"] = id;
            ViewBag.parkLotName = (await _parkingLotService.GetParkingLotById(id)).Value.name;
            ViewData["parkingSpotId"] = pSpotId;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult<ParkingSpotDTO>> Edit(int id, ParkingSpotDTO parkingSpotDTO, string pSpotId) {

            try {
                parkingSpotDTO.parkingLotID = id;
                parkingSpotDTO.parkingSpotID = pSpotId;

                //parkingSpotDTO.priceHour.ToString(CultureInfo.InvariantCulture);
                await _parkingSpotService.EditParkingSpot(id, parkingSpotDTO, pSpotId);

                return RedirectToAction("Details", "ParkingSpots", new { id, pSpotId });
            } catch (Exception) {

                return BadRequest();
            }
        }

    }
}

WebApp/Views/ParkingSpots/Create.cshtml
@model WebApp.DTO.ParkingSpotDTO

@{
    ViewData["Title"] = "Create";
}


<div>
    <div class="page-content page-container" id="page-content">
        <div class="padding">
            <div class="row container d-flex justify-content-center">
                <div class="col-xl-6 col-md-12">
                    <div class="card user-card-full">
                        <div class="row m-l-0 m-r-0">
                            <div class="col-sm-4 bg-c-lite-green user-profile">
                                <div id="park-spot-edit">
                                    <h2 class="f-w-600 spot-edit"><img id="img-park-create"src="https://res.cloudinary.com/du4r5hykw/image/upload/v1615806699/depositphotos_34747003-stock-illustration-parking-sign_fza3hy.png" alt="Alternate Text" /></h2>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="card-block">
                                    <h4 class="m-b-20 p-b-5 b-b-default f-w-600">Create Parking Spot</h4>
                                    <div class="row">
                                        <form asp-action="Create">
                                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                            <div class="form-group">
                                                <label asp-for="parkingSpotID" class="control-label">Designation</label>
                                                <input asp-for="parkingSpotID" class="form-control" />
                                                <span asp-validation-for="parkingSpotID" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="priceHour" class="control-label">Price/hour</label>
                                                <input asp-for="priceHour" class="form-control" />
                                                <span asp-validation-for="priceHour" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="floor" class="control-label">Floor</label>
                                                <input asp-for="floor" class="form-control" />
                                                <span asp-validation-for="floor" class="text-danger"></span>
                                            </div>
                                            <div class="form-group form-check">
                                                <label class="form-check-label">
                                                    <input class="form-check-input" asp-for="isPrivate" /> @Html.DisplayNameFor(model => model.isPrivate)
                                                </label>
                                            </div>
                                            <div class="form-group form-check">
                                                <label class="form-check-label">
                                                    <input class="form-check-input" asp-for="isCovered" /> @Html.DisplayNameFor(model => model.isCovered)
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="parkingLotID" class="control-label">Park</label>
                                                @Html.DropDownList("parkingLotID", new SelectList(ViewBag.allPlotsNames, "parkingLotID", "name"), new { @class = "form-control" })
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" value="Create" class="btn btn-primary" />
                                            </div>
                                            <div id="bk-ps" class="btn btn-secondary" style="width: 33%; margin-left:16.5em; margin-bottom:1em;">
                                                @Html.ActionLink("Back to List", "ManagerSpots", "ParkingSpots", new { id = ViewData["parkingLotId"] })
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/ParkingSpots/Details.cshtml
@model WebApp.DTO.ParkingSpotDTO

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div>
    <div class="page-content page-container" id="page-content">
        <div class="padding">
            <div class="row container d-flex justify-content-center">
                <div class="col-xl-6 col-md-12">
                    <div class="card user-card-full">
                        <div class="row m-l-0 m-r-0">
                            <div class="col-sm-4 bg-c-lite-green user-profile">
                                <div id="park-spot-details">
                                    <h2 class="f-w-600 spot">@Html.DisplayFor(model => model.parkingSpotID)</h2>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="card-block">
                                    <h4 class="m-b-20 p-b-5 b-b-default f-w-600">Parking Spot @ViewData["parkingSpotId"] Details</h4>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600">Designation</p>
                                            <h6 class="text-muted f-w-400"> @Html.DisplayFor(model => model.parkingSpotID)</h6>
                                        </div>
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600">Floor</p>
                                            <h6 class="text-muted f-w-400">@Html.DisplayFor(model => model.floor)</h6>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600">Covered</p>
                                            <h6 class="text-muted f-w-400"> @Html.DisplayFor(model => model.isCovered)</h6>
                                        </div>
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600">Private</p>
                                            <h6 class="text-muted f-w-400"> @Html.DisplayFor(model => model.isPrivate)</h6>
                                        </div>
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600">Price/hour</p>
                                            <h6 class="text-muted f-w-400"> €@Html.DisplayFor(model => model.priceHour)</h6>
                                        </div>
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600">Park Name</p>
                                            <h6 class="text-muted f-w-400"><p><strong>@ViewBag.parkLotName</strong></p></h6>
                                        </div>
                                        <div id="p-spots" class="btn btn-primary" style="width: 33%; margin-left:16.5em; margin-bottom:0.5em;">
                                            @Html.ActionLink("Edit", "Edit", "ParkingSpots", new { id = Model.parkingLotID, pSpotId = Model.parkingSpotID })
                                        </div>
                                        <div id="free-ps" class="btn btn-secondary" style="width: 33%; margin-left:16.5em; margin-bottom:1em;">
                                            @Html.ActionLink("Back to List", "ManagerSpots", "ParkingSpots", new { id = Model.parkingLotID })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApp/Views/ParkingSpots/Edit.cshtml
@model WebApp.DTO.ParkingSpotDTO

@{
    ViewData["Title"] = "Edit";
}

<div>
    <div class="page-content page-container" id="page-content">
        <div class="padding">
            <div class="row container d-flex justify-content-center">
                <div class="col-xl-6 col-md-12">
                    <div class="card user-card-full">
                        <div class="row m-l-0 m-r-0">
                            <div class="col-sm-4 bg-c-lite-green user-profile">
                                <div id="park-spot-edit">
                                    <h2 class="f-w-600 spot-edit">@ViewData["parkingSpotId"]</h2>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="card-block">
                                    <h4 class="m-b-20 p-b-5 b-b-default f-w-600">Parking Spot @ViewData["parkingSpotId"] Edit</h4>
                                    <div class="row">
                                        <form asp-action="Edit">
                                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                            <div class="form-group">
                                                <label>@Html.DisplayNameFor(model => model.parkingSpotID)</label>
                                                <p><strong><asp:TextBox ReadOnly="True">@ViewData["parkingSpotId"]</asp:TextBox></strong></p>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="priceHour" class="control-label"></label>
                                                <input asp-for="priceHour" class="form-control" type="text" />
                                                <span asp-validation-for="priceHour" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <label asp-for="floor" class="control-label"></label>
                                                <input asp-for="floor" class="form-control" />
                                                <span asp-validation-for="floor" class="text-danger"></span>
                                            </div>
                                            <div class="form-group form-check">
                                                <label class="form-check-label">
                                                    <input class="form-check-input" asp-for="isPrivate" /> @Html.DisplayNameFor(model => model.isPrivate)
                                                </label>
                                            </div>
                                            <div class="form-group form-check">
                                                <label class="form-check-label">
                                                    <input class="form-check-input" asp-for="isCovered" /> @Html.DisplayNameFor(model => model.isCovered)
                                                </label>
                                            </div>
                                            <div class="form-group">
                                                <p><strong>@ViewBag.parkLotName</strong></p>
                                                <p type="hidden" class="hidden readonly">@Html.DisplayFor(model => model.parkingLotID)</p>

                                                <p asp:HiddenField type="hidden" style="visibility: hidden;" class="hidden readonly">@Html.TextBox("ParkingLotID", ViewData["parkingLotId"], new { @readonly = "readonly" })</p>
                                            </div>
                                            <div class="form-group">
                                                <input id="save-btn" type="submit" value="Save" class="btn btn-primary" />
                                            </div>
                                            <div id="bk-ps" class="btn btn-secondary" style="width: 33%; margin-left:16.5em; margin-bottom:1em;">
                                                @Html.ActionLink("Back to List", "ManagerSpots", "ParkingSpots", new { id = ViewData["parkingLotId"] })
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/ParkingSpots/Free.cshtml
@model IEnumerable<WebApp.DTO.ParkingSpotDTO>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.parkLotName</h2>
<h3>Free Parking Spots</h3>
<br>

<div class="table-manage-spots">
    <table class="table" style="width:50%">
        <thead class="thead-dark">
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.parkingSpotID)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.priceHour)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-hover">
                    <td class="tablehover pointer" onclick="location.href = '@Url.Action("Details", new { id = ViewData["parkingLotId"], pSpotId=item.parkingSpotID })'">
                        @Html.DisplayFor(modelItem => item.parkingSpotID)
                    </td>
                    <td>
                        €@Html.DisplayFor(modelItem => item.priceHour)
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="back-park-button">
        @Html.ActionLink("Back to Parking Lot", "Details", "ParkingLots", new { id = ViewData["parkingLotId"] })
    </div>

</div>

WebApp/Views/ParkingSpots/Index.cshtml
@model IEnumerable<WebApp.DTO.ParkingSpotDTO>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.parkLotName</h1>
<h6>ALL PARKING SPOTS</h6>

<p style="text-align:left;">
    <a style="color:red; font-size:18px" asp-action="Create">New ParkingSpot</a>
</p>



<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Designation</a>
            </th>
            <th style="text-align:right;">
                <a asp-action="Index" asp-route-sortOrder="@ViewData["ParkingLotSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Price/hour</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr class="table-hover">
                <td class="tablehover pointer" onclick="location.href = '@Url.Action("Details", new { id = ViewData["parkingLotId"], pSpotId = item.parkingSpotID })'">
                    @Html.DisplayFor(modelItem => item.parkingSpotID)
                </td>
                <td style="text-align:right;">
                    €@Html.DisplayFor(modelItem => item.priceHour)
                </td>
            </tr>
        }
        <tr>
            <td>
                @Html.ActionLink("Back to Parking Lot", "Details", "ParkingLots", new { id = ViewData["parkingLotId"] })
            </td>
        </tr>
    </tbody>
</table>

WebApp/Views/ParkingSpots/ManagerSpots.cshtml
@model IEnumerable<WebApp.DTO.ParkingSpotDTO>

@{
    ViewData["Title"] = "ManagerSpots";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.parkLotName</h1>
<br>
<h2>Spots Management</h2>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>

<div class="table-manage-spots">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.parkingSpotID)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.priceHour)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.floor)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.isPrivate)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.isCovered)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td class="tablehover pointer" onclick="location.href ='@Url.Action("Details",new { id = ViewData["parkingLotId"], pSpotId=item.parkingSpotID })'">
                        @Html.DisplayFor(modelItem => item.parkingSpotID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.priceHour)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.floor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.isPrivate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.isCovered)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "ParkingSpots", new { id = ViewData["parkingLotId"], pSpotId = item.parkingSpotID }) |

                        @Html.ActionLink("Edit", "Edit", "ParkingSpots", new { id = ViewData["parkingLotId"], pSpotId = item.parkingSpotID })
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="back-park-button">
        @Html.ActionLink("Back to Parking Lot", "Details", "ParkingLots", new { id = ViewData["parkingLotId"] })
    </div>
</div>
<div class="back-park-button"><a asp-controller="Home" asp-action="Index">Back to Home</a></div>